### ISSUE TITLE
Invalid err variable reference: "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by atc0005** [atc0005/mysql2sqlite#71]
From a `master` branch build of the `check_mysql2sqlite` binary:

> CRITICAL: plugin crash detected. See details via web UI or run plugin manually via CLI.
> 
> **ERRORS**
> 
> * plugin crash/panic detected: runtime error: invalid memory address or nil pointer dereference
> 
> **THRESHOLDS**
> 
> * CRITICAL: Non-recoverable error, requires sysadmin intervention
> * WARNING: Recoverable error, potentially resolved with the next database sync job
> 
> **DETAILED INFO**
> 
> <pre>
> runtime error: invalid memory address or nil pointer dereference
> 
> goroutine 1 [running]:
> github.com/atc0005/go-nagios.(*ExitState).ReturnCheckResults(0xc0000aa488)
>         github.com/atc0005/go-nagios@v0.6.0/nagios.go:148 +0xa6f
> panic(0x7f8020, 0xa50c30)
>         runtime/panic.go:975 +0x47a
> main.main()
>         github.com/atc0005/mysql2sqlite/cmd/check_mysql2sqlite/main.go:306 +0x4fb9
> 
> </pre>

**Comment by atc0005** [comment]
Current code:

https://github.com/atc0005/mysql2sqlite/blob/e2dd455bd406328f03a54a144c990b3a7b247fcb/cmd/check_mysql2sqlite/main.go#L302-L316

In this case, the `rowsCountErr` variable should be referenced, not `err`.

**Comment by atc0005** [comment]
I didn't spot the same problem with the `mysql2sqlite` binary. For that app, it appears that `err` was consistently used.
